###

GET http://localhost:3000/api/productos

###
POST http://localhost:3000/api/productos
Content-Type: application/json

{
    "nombre": "banana",
    "precio":8
}

###

GET http://localhost:3000/api/productos/3

###

POST http://localhost:3000/api/productos HTTP/1.1
Content-Type: application/json

{ 
    "nombre": "banana", 
    "precio": 10 
}

###

PUT http://localhost:3000/api/productos/3 HTTP/1.1
Content-Type: application/json

{ 
    "nombre": "galletas Maria", 
    "precio": 6 
}

###
DELETE http://localhost:3000/api/productos/4